// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © lruczu

//@version=5
indicator("Stopping formation", overlay=true, max_labels_count = 50)

// mlot - bullsh case
// wisielec - bearish case

//var candle = box.new(0, 0, 0, 0, bgcolor=color.new(color.blue, 90))

is_stopping_formation(prop) =>
    if close > open // green
        if math.abs(open - low) / math.abs(open - close) < prop
            1
        else
            0
    else // red
        if math.abs(open - high) / math.abs(open - close) < prop
            -1
        else
            0

code = is_stopping_formation(0.01)
if code == 1
    label.new(bar_index, high, color=color.new(color.green, 70))
else if code == -1
    label.new(bar_index, high, color=color.new(color.red, 70))
